server:
  port: 7771

spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        namespace: @profiles.active@
        server-addr: ${NACOS_HOST:aeaimb-register}:${NACOS_PORT:8848}
      config:
        namespace: @profiles.active@
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
  config:
    import:
      - nacos:application.yml
      - nacos:${spring.application.name}.yml

